### ISSUE TITLE
Security Issue: Credentials shouldn't be public

### ISSUE THREAD

**Issue by anubhav8804602148** [shreya361999/ReportGeneration#1]
Please do not store password directly in properties file. 
Put it in environment variables and read from there. 

Issue location: src/main/resources/application.properties

**Comment by shreya361999** [comment]
Thank you for letting me know.
I have made the changes and pushed it.
Please check.

**Comment by anubhav8804602148** [comment]
Good! Please use environment variable for all parameters which can very across multiple environments. 
E.g. URLs, User Ids, Passwords,
