### ISSUE TITLE
Add logger to the application

### ISSUE THREAD

**Issue by anubhav8804602148** [shreya361999/ReportGeneration#2]
Please add a logger implementation to the application. (log4j would be good). PFB properties 
1.  Logs should be archived on daily basis. 
2. Current days log file should be named: ${APPLICATION_NAME}_${ENV}_${APPLICATION_VERSION}.log
3. Archived logs should be named: ${APPLICATION_NAME}_${ENV}_${APPLICATION_VERSION}_${DATE}.log

**Comment by shreya361999** [comment]
Have added logger in the code.
Please check
