### ISSUE TITLE
Update logic to update createdBy or updatedBy

### ISSUE THREAD

**Issue by anubhav8804602148** [shreya361999/ReportGeneration#4]
Since anyone can send the request by Postman, they may choose not to include createdBy field. To handle such scenario, do not accept createdBy or UpdatedBy field from requestBody. 
Capture host provided in headers.
If this is not included in the request to create a project, then do not allow to create project and send "BAD_REQUEST - User header missing" error. 
<img width="589" alt="image" src="https://github.com/shreya361999/ReportGeneration/assets/62458295/5977b773-28a5-40a0-afba-af0cdfd3e73c">

**Comment by shreya361999** [comment]
Have made the changes.
